[lint]
pycodestyle.max-line-length = 100 # defaultních 80 bývá zbytečně krátké
select = ["ALL"]
ignore = [
    # Dokumentace (pydocstyle)
    "D",       # Ignoruje kompletně celou sadu pravidel pro docstringy

    # Využití os pro práci s cestami místo pathlib
    "PTH",     # Povoluje všechny metody os, které by v moderním kódu měly být narhazeny alternativou z pathlib

    # Typové anotace (flake8-annotations / future-annotations)
    "ANN002",  # Nevyžaduje typování pro *args
    "ANN003",  # Nevyžaduje typování pro **kwargs
    "ANN204",  # Nevyžaduje typování návratové hodnoty u __init__ (např. -> None)
    "ANN401",  # Povoluje typ 'Any', pokud nevíme, který typ použít
    "FA102",   # Nevyžaduje import 'from __future__ import annotations' pro starší Python

    # Kvalita a formát kódu
    "T201",    # Povoluje funkci print() (neučíme pořádný logging)
    "ERA001",  # Povoluje zakomentovaný kód v souborech
    "RET504",  # Povoluje přiřazení do proměnné těsně před 'return', často to tak ukazujeme
    "SIM105",  # Povolit jednoduche `try... except: pass` pro zamlčení chyb
    "SIM108",  # Nenutí používat ternární operátor (if-else na jednom řádku)
    "UP015",   # Povoluje explicitní "r" u funkce open() (čtení je defaultní způsob otevření souboru)
    "UP035",   # Povoluje importovat typy z 'typing' (např. Callable), i když už jsou v 'collections.abc'
    "COM812",  # Nevyžaduje koncovou čárku u víceřádkových seznamů/n-tic
    "COM819",  # Povoluje přebytečnou čárku na konci jednořádkového seznamu
    "PERF401", # Nevynucuje narhazení for cyklů za list comprehensiony (či list.extend)
    "PLR2004", # Nezakazovat plošně magické konstanty
    "FBT",     # Tuto konvenci nemůžeme dodržet bez výuky https://peps.python.org/pep-3102/

    # Formát "TODO"
    "TD",      # Nevynocovat žádný formát. Samotné "TODO" je stále zvýrazněno jako "FIX002"

    # Architektura
    "INP001",  # Nevyžaduje __init__.py v každé složce (není vyučováno)

    # Importy
    "I001",    # Vypíná vynucování řazení importů
]